version: "2"
services:
    webdav:
        container_name: webdav
        image: mirorauhala/webdav
        ports:
            - 8080:8080
        volumes:
            - $HOME/docker/webdav:/media
        environment:
            - USERNAME=webdav
            - PASSWORD=webdav
            - UID=1000
            - GID=1000
            - TZ=Europe/Helsinki
        networks:
            - web
        labels:
            - traefik.enable=true
            - traefik.http.routers.webdav.rule=Host(`cloudstorage.rauhala.dev`)
            - traefik.http.services.webdav.loadbalancer.server.port=8080
            - traefik.http.routers.webdav.entrypoints=https
            - traefik.http.routers.webdav.tls=true
            - traefik.http.routers.webdav.tls.certresolver=http
            - traefik.http.routers.webdav.tls.domains[0].main=rauhala.dev
            - traefik.http.routers.webdav.tls.domains[0].sans=*.rauhala.dev
            - traefik.http.routers.webdav.middlewares=webdav-cors@docker
            - traefik.http.middlewares.webdav-cors.headers.framedeny=true
            - traefik.http.middlewares.webdav-cors.headers.browserxssfilter=true
            - traefik.http.middlewares.webdav-cors.headers.accesscontrolallowmethods=GET,OPTIONS,PUT
            - traefik.http.middlewares.webdav-cors.headers.accesscontrolalloworiginlist=https://*.rauhala.dev
            - traefik.http.middlewares.webdav-cors.headers.accesscontrolmaxage=100
            - traefik.http.middlewares.webdav-cors.headers.addvaryheader=true

networks:
    web:
        external: true
